### ISSUE TITLE
几个小问题

### ISSUE THREAD

**Issue by hanyh2004** [chengzhx76/Weixin-Dubbo#1]
1,weixin-service-message module里面的
TestMain第5行的的MsgType是不是应该换一下
//import com.cheng.weixin.rpc.message.enums.MsgType;
import com.cheng.weixin.rabbitmq.enums.MsgType;

2，weixin-service-order里面 TestMain的目录结构没有建正确

**Comment by chengzhx76** [comment]
我的疏忽，已修改
